### ISSUE TITLE
Bug at CameraXBasic example : camera switch 

### ISSUE THREAD

**Issue by davinnovation** [android/camera#37]
When calling bindCameraUseCases at `camera_switch_button` click listener, it doesn't work correctly with Galaxy S10+, Note 8

If I add `CameraX.unbindAll()` code to `bindCameraUseCases()` function at start line, it works normarlly. 

```
private fun bindCameraUseCases() {
        CameraX.unbindAll()
        ...
}
```

**Comment by Tooto** [comment]
Work for me! (Samsung note 9)

**Comment by owahltinez** [comment]
@davinnovation does this happen 100% of the time? Do you see any errors in logcat?

**Comment by Tooto** [comment]
> @davinnovation does this happen 100% of the time? Do you see any errors in logcat?

100%. Tested on sgs6, sgnote 9.

`
2019-07-18 13:08:40.998 373-373/com.motify.client E/CameraFragment$updateCameraUi: java.lang.IllegalArgumentException: Exceeded max simultaneously bound image capture use cases.
        at androidx.camera.camera2.impl.UseCaseSurfaceOccupancyManager.checkUseCaseLimitNotExceeded(UseCaseSurfaceOccupancyManager.java:61)
        at androidx.camera.camera2.impl.Camera2DeviceSurfaceManager.getSuggestedResolutions(Camera2DeviceSurfaceManager.java:150)
        at androidx.camera.core.CameraX.calculateSuggestedResolutions(CameraX.java:494)
        at androidx.camera.core.CameraX.bindToLifecycle(CameraX.java:188)
`

**Comment by davinnovation** [comment]
@owahltinez Yes. When I press the switch button, 100%. - Galaxy S10+ confirmed

In logcat, error occurred just one time with this message
```
2019-07-18 20:24:29.535 4188-4239/com.android.example.cameraxbasic E/Camera: CameraDevice.onError(): 1 with error: ERROR_MAX_CAMERAS_IN_USE
```
After this, error message doesn't shown and only this message has logged when
```
2019-07-18 20:23:13.619 392-392/com.android.example.cameraxbasic D/ViewRootImpl@705f68f[MainActivity]: ViewPostIme pointer 0
2019-07-18 20:23:13.644 392-392/com.android.example.cameraxbasic D/ViewRootImpl@705f68f[MainActivity]: ViewPostIme pointer 1
```

**Comment by owahltinez** [comment]
OK, the problem is that when the camera switch button is pressed, we are trying to bind all camera use cases without unbinding the previous ones first. Thanks for flagging!

I think that the proper solution here would be to call `CameraX.unbindAll()` inside of the switch button callback, rather than inside of the `bindCameraUseCases()` function.
